apiVersion: v1
baseDomain: ocp-dev.datacomm.co.id
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cluster-jkt01
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfOTNiYWU3NzlmMDNiNGMzY2FmZWQwYzBlY2FmYTc2MDE6QjhUNEJLS01SNkhOWUswR1pLRDVXSDNIUUxJWkNGTkhMMU1LREU1VlA5M0xWMVZMWVE3QVJMTjBVMFk4WkpZSQ==","email":"nam.khong@datacomm.co.id"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfOTNiYWU3NzlmMDNiNGMzY2FmZWQwYzBlY2FmYTc2MDE6QjhUNEJLS01SNkhOWUswR1pLRDVXSDNIUUxJWkNGTkhMMU1LREU1VlA5M0xWMVZMWVE3QVJMTjBVMFk4WkpZSQ==","email":"nam.khong@datacomm.co.id"},"registry.connect.redhat.com":{"auth":"NTM1NzU1ODB8dWhjLTFleFU4bTlXbmpQbFZCOGZ3bjRQNWFnM25DSDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTNaRGd6WW1RME9ERXhOVFUwT1dZNVlqRmxNRGMxWTJKaE4yUXpOemMwT0NKOS5BaHY2bWFqWGQ2bUUtMVhFeDBhOE1SdWtzREFjMnBsMkRlTmNqeVFEMzBsVWJRREZZQkNjMW1sWWRueVp1SDkwMkFzV24yV25EN283QlExSWVNbUNQenViYUh3eXIwRjFMeTR5ZklVbDh1a0pPaktBOUd6TVplRm5NVUE5TE1jS3h0U1hSZTRnTzRWOVNZQ09la3J4T05NQ3h6TjFOZ1JqQTlCRUprNUhnanJNVlUyRHBmd0Nhc0ZNZVdZNG90bkFxOVlleFlDQXp4YXAxUDN2WGtrZnFNU1dEREpxYVhxTVpqeGNrazV5SzNvOE0ycS0tZldEeVJ1RzkyQ3NRSEFBTnQ0NE5oWDY2b2kyTzhaQnZYakdiMUZkOWRlbFBOVVFyaTgtZW5aVDFIQ2xHY1VPdHE1N01qb2pmd3VoTjZQZlpTR1pDcWMzSTZsUmp5VTBLLWNCSGV3TjJja3NweWdIYXh5RS1YNklfRlVZWnpFYUpFblRoa2hJYlJZVC1ndVZ0eEZSUUt4VTBKeTZZUUhKZXpiVnZWOGxMVmRMM2paUWlsSG1ja0N4aHNCZ0pyYXBuT0xzdTJ5TjQ2X1QtQXNYblNuX0VsNlE3ODYyUW5ibmlUZUkyZHZyQTV6T0EwLUNxQ0VXbmZFX2J0NVExMmFaaldERlFBMmR2Y1h6ckpSbXJ6alVweVl4MmlTX1lYeEt6OXc3VUdtQ0dCVm5BV3BJWU1NRGNiMGhCbThRbmhkNXdSZ0c4R01DcXBHZnNTdXJnMWhTLVo0MG9TdTJ4M2IxU082VDZIRnROelFjSWRnNnN2bHRjdFlhOFNHOE9hUzhsSXc0OEVDekpFR242UU5tWGVGREdyc2xXNklMUGZ6TGllT1NiWGZ1LXNXNUN3Z1pIbWxOQTNmcGZLTQ==","email":"nam.khong@datacomm.co.id"},"registry.redhat.io":{"auth":"NTM1NzU1ODB8dWhjLTFleFU4bTlXbmpQbFZCOGZ3bjRQNWFnM25DSDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTNaRGd6WW1RME9ERXhOVFUwT1dZNVlqRmxNRGMxWTJKaE4yUXpOemMwT0NKOS5BaHY2bWFqWGQ2bUUtMVhFeDBhOE1SdWtzREFjMnBsMkRlTmNqeVFEMzBsVWJRREZZQkNjMW1sWWRueVp1SDkwMkFzV24yV25EN283QlExSWVNbUNQenViYUh3eXIwRjFMeTR5ZklVbDh1a0pPaktBOUd6TVplRm5NVUE5TE1jS3h0U1hSZTRnTzRWOVNZQ09la3J4T05NQ3h6TjFOZ1JqQTlCRUprNUhnanJNVlUyRHBmd0Nhc0ZNZVdZNG90bkFxOVlleFlDQXp4YXAxUDN2WGtrZnFNU1dEREpxYVhxTVpqeGNrazV5SzNvOE0ycS0tZldEeVJ1RzkyQ3NRSEFBTnQ0NE5oWDY2b2kyTzhaQnZYakdiMUZkOWRlbFBOVVFyaTgtZW5aVDFIQ2xHY1VPdHE1N01qb2pmd3VoTjZQZlpTR1pDcWMzSTZsUmp5VTBLLWNCSGV3TjJja3NweWdIYXh5RS1YNklfRlVZWnpFYUpFblRoa2hJYlJZVC1ndVZ0eEZSUUt4VTBKeTZZUUhKZXpiVnZWOGxMVmRMM2paUWlsSG1ja0N4aHNCZ0pyYXBuT0xzdTJ5TjQ2X1QtQXNYblNuX0VsNlE3ODYyUW5ibmlUZUkyZHZyQTV6T0EwLUNxQ0VXbmZFX2J0NVExMmFaaldERlFBMmR2Y1h6ckpSbXJ6alVweVl4MmlTX1lYeEt6OXc3VUdtQ0dCVm5BV3BJWU1NRGNiMGhCbThRbmhkNXdSZ0c4R01DcXBHZnNTdXJnMWhTLVo0MG9TdTJ4M2IxU082VDZIRnROelFjSWRnNnN2bHRjdFlhOFNHOE9hUzhsSXc0OEVDekpFR242UU5tWGVGREdyc2xXNklMUGZ6TGllT1NiWGZ1LXNXNUN3Z1pIbWxOQTNmcGZLTQ==","email":"nam.khong@datacomm.co.id"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1cOLV374RT5timOHT7ZV6h6mMsMthZ50IhLXl/EXSI/Jgz9JD6DsSk95ZglpQtWJbQ5UyQpYIE/CxS2c8Hq3rW+Mk3ae85nB5T8oO/5fVRV09Gs3dnH85rPKIG2wEoHqnk9x99tP0PIxsUBHg1SL9ONMrYaUmyuKpKUbBg0awYXBRermxwB7b4ASje2Q/gt/Uvmtqix83F36QK2U1n1h8Kbhu9Wa/UozJaH3aLhJRjTAcZC/DjeHAnU1cfWde979ok1HEcxOha7vcv2sHhxHP3tjro0IJA0Lh7/qHhy7LiLVXMo9VnN/eE4aJeHgcFT3lGlXd01Zmi+3TE7XfZqpvZCQSUswBR0uLNeO5QJQOsKa4/EcSwGrEtl1sYJntKXtIR3z48VDVNtpsztegcJLI62I72mpNn/XnVbmUK/+OpgCGQyDfNfc7CEqXyiEmNwkPcb+arWqDgRK6VAaZR5mtuwnXxi97IJgKYCaoxDQImCdEURNJ0/jKvB8htgLyyZ1MikvxA6ePQ4u4sNkZxI8xKiuqAplsoFNIrb+sNsd6i51wbrbiGTWuWSvPBITgq4qN2dfM+hF7ykbLMn9Eedqx0MZjG4eAIuJ8+vnJLm+gl+oxxWgFtfrE6KRRmoEezH8r7KYQVC2wX9ScrGDULWbWVtxY3b17wjQkbXcM/C4ulw== teguh.imanto-datacomm@bastion.ocp-dev.datacomm.co.id'












